### ISSUE TITLE
Open source license and readme

### ISSUE THREAD

**Issue by juliocnsouzadev** [Riposati/jogo_packman#1]
Gustavo add uma lincença open source para seus projetos, assim quem for fazer um fork ou um download de seu projeto saberá como pode utilizá-lo. O Github provê vários modelos, é só criar um arquivo com o nome de LICENSE.MD que ele mostra uma lista de modelos e tipos.

![license](https://cloud.githubusercontent.com/assets/3652062/15422909/38da9e74-1e51-11e6-9639-4d75439f3eb8.png)

Aproveita e coloca um readme nesse do packman, tipo o que fazer depois de copiar como se tem q compilar qual versão de compilador etc... tem muita gente noobie em C como eu que ia curtir rodar esse projeto, se der add uma pasta na raiz com executáveis :D . 

abs

**Comment by Riposati** [comment]
Valeu julio pelo interesse brigadao mesmo velho vou fazer isso então que
você me disse hehe agora é rumar pro c++ pq ele tem algoritmos úteis na STL
pra agilizar no processo de implementação de estruturas mais complexas tipo
o mapa que é uma árvore balanceada rubro negra. Abraços
Em 20 de mai de 2016 06:16, "Julio CN Souza" notifications@github.com
escreveu:
